### ISSUE TITLE
Formulas Not Displaying Properly in github.io version

### ISSUE THREAD

**Issue by alexander-ye** [AllenDowney/ThinkBayes2#67]
Formulas in the github.io version of the book are not displaying properly&mdash;they are still in their raw LaTeX syntax.

Exmaple: https://allendowney.github.io/ThinkBayes2/chap02.html

**Comment by joac** [comment]
As a workaround I'm pasting on the page console
```javascript
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  },
  svg: {
    fontCache: 'global'
  }
};

(function () {
  var script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js';
  script.async = true;
  document.head.appendChild(script);
})();
```
To activate matjax [Source](https://docs.mathjax.org/en/latest/web/configuration.html#configuring-and-loading-in-one-script)

I didn't found the spinxh config. @AllenDowney If you can point me in the right direction I can provide a pr to fix it.

**Comment by Bearsetc** [comment]
@AllenDowney - The myst extension attrs_inline seems to be causing the conflict with dollarmath. Please try the update to _config.yml shown below. I have not checked if you use the attrs_inline feature in the book, but if you can live without it, hopefully this is a fix. Happy Holidays!

```yaml
parse:
  # myst_extended_syntax: true  # deprecated, instead enable individual features below
  myst_enable_extensions:  # https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    # - attrs_inline  # causing the conflict with dollarmath
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist
```
